### ISSUE TITLE
能不能把窗口最小宽度和高度调整下

### ISSUE THREAD

**Issue by mayingfeng** [642661520/vuelayer#1]
有的弹出框只需要很小一个窗口，但是你的最小宽度和高度设置为300px和200px，我有的弹出框不需要这么大

**Comment by 642661520** [comment]
你好，谢谢你的反馈，针对这个情况，我考虑近期增加配置项可以设置最小高宽。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "642661520/vuelayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月21日(星期一) 上午9:54
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[642661520/vuelayer] 能不能把窗口最小宽度和高度调整下 (#1)





 
有的弹出框只需要很小一个窗口，但是你的最小宽度和高度设置为300px和200px，我有的弹出框不需要这么大

**Comment by 642661520** [comment]
> 有的弹出框只需要一个窗口，但是你的最小宽度和设置高度为300px和200px，我有的弹出框不需要这么大

0.1.7版本，已添加该功能，配置项：minarea，可以测试下

**Comment by guigui0326** [comment]
建议增加最大宽度设置，比如设置90%的宽，在移动设备刚刚好，pc端的话就会特别大。

**Comment by 642661520** [comment]
你这个使用场景是什么样？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Firstmeet·初见 ***@***.***&gt;
发送时间: 2021年9月29日 15:14
收件人: 642661520/layer-vue ***@***.***&gt;
抄送: final summer ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[642661520/layer-vue] 能不能把窗口最小宽度和高度调整下 (#1)





 
建议增加最大宽度设置，比如设置90%的宽，在移动设备刚刚好，pc端的话就会特别大。
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
